name: Server > Build

on:
  push:
    branches: ['**']
    paths:
      - server/**
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v5
        with:
          sparse-checkout: server
          sparse-checkout-cone-mode: false

      # build the action
      - uses: jdx/mise-action@v2

      - run: npm ci
      - run: npm run test
      - run: npm run build
